// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdwgmombcqeewkqafdrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkd2dtb21iY3FlZXdrcWFmZHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NTQ3MzEsImV4cCI6MjA2MzUzMDczMX0.HTpfn1AqLtienGCcwoaDMRxgE4xYHqm6SQo2foZ6-EA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);